### ISSUE TITLE
Type Doc crashing when navigating to any other page

### ISSUE THREAD

**Issue by ayushpaharia** [DappioWonderland/gateway#18]
I was running the project by -
yarn install to yarn typedocGen to yarn typedocServe

The server seems to run properly here

Clicking on any subpage like
image

Throws error

Request for /favicon.ico by method GET
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/home/ayush/Desktop/box/solana/dappio/gateway/src/doc/favicon.ico'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/ayush/Desktop/box/solana/dappio/gateway/src/doc/favicon.ico'
}
error Command failed with exit code 1.

I added a favicon.ico to /src that solves this issue.

**Comment by ironaddicteddog** [comment]
Resolved by #23
